# Generated by Django 4.1.5 on 2023-08-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='special_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/specialOffer_img')),
                ('name', models.CharField(max_length=100)),
                ('Link', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Link',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
